// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiaJtHIM6SgajPWWX5EiF7q14s7zP1z8k',
    appId: '1:254049091226:web:02cd3b682d41bcc7ba2923',
    messagingSenderId: '254049091226',
    projectId: 'medscan-473c5',
    authDomain: 'medscan-473c5.firebaseapp.com',
    storageBucket: 'medscan-473c5.firebasestorage.app',
    measurementId: 'G-82XN2VYLBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYFx0VQ2uy67JkT5uIbYKgUEvEwTuaoMI',
    appId: '1:254049091226:android:c66f612ea9b3c095ba2923',
    messagingSenderId: '254049091226',
    projectId: 'medscan-473c5',
    storageBucket: 'medscan-473c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDjF0DZLeVfvT09akeQ_n9TkG5whMzSp8',
    appId: '1:254049091226:ios:fbb5e80d5a96a187ba2923',
    messagingSenderId: '254049091226',
    projectId: 'medscan-473c5',
    storageBucket: 'medscan-473c5.firebasestorage.app',
    iosBundleId: 'com.example.medscan',
  );
}
